### ISSUE TITLE
Add publiccode.yml file

### ISSUE THREAD

**Issue by libremente** [uniurbit/UniSD#1]
Buongiorno @cappe87 @enricouniurb,

penso che questo progetto potrebbe essere ottimo da inserire nel catalogo del software di Developers Italia!
Se vi serve una mano per fare il file publiccode.yml (https://publiccode-editor.developers.italia.it/) resto a disposizione.

Grazie!

**Comment by cappe87** [comment]
Fatto! dovevamo fare gli ultimi controlli. 

Grazie
